Proceso sin_titulo
	//VARIABLE STRING RECIBE CADENA DE TEXTO
	varString <- "Yaneth"
	//VARIABLE RECIBE UN CARACTER DE TEXTO
	varChar <- "y"
	//VARIABLE QUE RECIBE NUMEROS ENTEROS
	varInt <- 0
	//VARIABLE QUE RECIBE NUMEROS DECIMALES
	varFloat <- 0.5
	//VARIABLE TIPO ARREGLO
	//TRABAJA CON  UN CONJUNTO DE DATOS DEL MISMO TIPO EJEMPLO SI SON NUMEROS O SI SON LETRAS
	//SINTAXIS: SE TRABAJA CON DIMENSION nombreArray[tamaño del array]
	Dimension numeros[7]
FinProceso
